- python/replicate/config.py
- python/replicate/project.py
- python/tests/test_experiment.py
If .replicate/storage exists, this obliterates replicate.yaml
> Only use backwards compatible storage if no config

- Makefile
CI doesn't do this any longer, so just removing to be consistent.
> Remove upload binaries from release-manual

- go/Makefile
- python/Makefile
- python/setup.py
Compilation fails / throws warnings because some of our dependencies
don't support 32 bit. This also speeds up build.
Tensorflow and PyTorch don't work on 32 bit. I think it's fairly safe
to say we don't need to support it for now, maybe we can add back in
future if we do.
> Remove 32 bit support

- python/replicate/checkpoint.py
This was a regression, plot labels went missing from `experiments.plot()` when I added `experiment.checkpoints.plot()`
> add missing plot labels on checkpoints/experiments

- python/replicate/constants.py
- python/replicate/exceptions.py
- python/replicate/experiment.py
- python/replicate/project.py
- python/tests/test_experiment.py
- python/tests/test_project.py
This allows us to upgrade to better storage mechanisms in the
future. A project must use a single consistent repository version.
A file called project.json is written to the top level of the
project's repository. That file is checked on replicate.init(), and if
a newer version is detected, the experiment fails to start.
> Save repository version at project level

- go/pkg/repository/repository.go
- go/pkg/repository/repository_test.go
Where virtualenvs are defined as folders containing a pyvenv.cfg file.
> Always ignore virtualenvs

- Makefile
- makefile-scripts/verify-go-version.sh
- makefile-scripts/verify-python-version.sh
Run on make build/develop, checks that Go, Python, and pip are all installed on the PATH and at the correct versions.
If not, points to recommended install instructions.
> Make targets to verify that Go and Python are installed correctly

- end-to-end-test/conftest.py
- python/tests/repository/test_s3_repository.py
The problem was heartbeats were running, and the heartbeat recreated the bucket after the test deleted it. I've also included a couple of other improvements, deets in comments.z
> Fix S3 buckets getting left over in tests

- python/tests/test_heartbeat.py
The real fix is #436, but this is blocked on #408. I have reverted previous attempt at fixing, because I think this just slows down tests and doesn't actually fix.
> Disable flakey heartbeat test

- python/replicate/experiment.py
- python/tests/test_experiment.py
`checkpoint()` now auto-increments the step number if the `step` argument is not provided.
Fixes #276, fixes #296
Signed-off-by: justinchuby <justinchuby@users.noreply.github.com>
> Auto-increment step number in checkpoint

- python/tests/repository/test_s3_repository.py
This is a weird test, because we test stuff like this in
test_experiment.py. What we're really checking is that saving
experiments in S3 saves the experiment file in the right place
with roughly the right data, so I've made it less brittle.
> Fix python_version in external tests

- go/pkg/cli/checkout.go
- go/pkg/cli/checkout_test.go
- go/pkg/repository/cached.go
- go/pkg/repository/disk.go
- go/pkg/repository/disk_test.go
- go/pkg/repository/gcs.go
- go/pkg/repository/repository.go
- go/pkg/repository/repository_test.go
- go/pkg/repository/s3.go
- web/pages/docs/reference/cli.mdx
Issue #358 
There are some design decisions to make, so I thought let's discuss them first before implementing a complete solution in subsequent commits.
- I have created a new method in the Repository interface - `GetPathItemTar()` - that allows the user to specify which file/directory they want to extract from the tar ball. This method will be called from `checkoutCheckpoint()` in `checkout.go`
- The solution revolves around using `TarGz.Extract(source, target, destination)`. However, it looks like if the `target` does not exist inside the tar, `Extract` does not throw errors. So I added some code to handle that case.
- Since all files in the tarball are prefixed with the tar file's name, argument `target` in `Extract()` must also contain that prefix, else it will fail to locate the …
> Allow checking out individual files and directories

- Makefile
We want to update website on release so docs represent released version, but also allow us to change website between releases.
https://replicate.ai is now deployed from the `website` branch. On release, push to this branch. If we want to do hotfixes for the website, we can cherry-pick from `main` to the `website` branch.
For simplicity, release force pushes to `website` and will blow away any hot fixes. We'll have to be disciplined and make sure we always cherry-pick from `main`.
This is intended as a really lightweight "release" branch sort of thing. We could do more complex things (merging changes instead of blowing away hotfixes, documentation versioning, etc) but this seemed like the simplest thing that achieves what we want.
Note: I haven't actually tested this, so we'll need to …
> Push to website branch on release

- go/pkg/repository/s3_test.go
Missed this one in #411 because I think my code search was broken??
Anyway -- this is a new failure because the repository manifest is
now created, which now creates the bucket.
> Delete buckets after test in Go S3 test

- go/pkg/cli/daemon.go
- go/pkg/files/files.go
- go/pkg/project/project.go
- go/pkg/repository/repository.go
- go/pkg/repository/repository_test.go
- python/replicate/daemon.py
- python/replicate/project.py
This solves the bug where archive fails when files in the archive are written during archival.
Also adds a `debug` argument to `replicate.init()`, that enables verbose server logs.
> Copy files before background upload

- go/pkg/project/checkout.go
- go/pkg/project/checkout_test.go
- go/pkg/project/project.go
- Show messages before copying so it doesn't hang and look broken
- If no path has been passed, throw error.
- If path has been provided but no data exists, throw error.
> Better checkout messages

- go/pkg/cli/show.go
- go/pkg/project/project.go
- go/pkg/shared/serve.go
- python/tests/test_experiment.py
There was an incomplete implementation in #485. It wasn't being passed through the stack correctly. Also added
some sanity tests for the Python -> Go -> Python round trip.
As an aside, there are so many places that new fields need to be added. I wonder if there is a way this can be simplified, or the test can be generalized to get the round trip always works.
`config` is also kind of broken, but low priority. #492
> Fix Python version

- go/pkg/cli/diff_test.go
- go/pkg/cli/show.go
- go/pkg/cli/show_test.go
- go/pkg/slices/slices.go
- web/pages/docs/reference/cli.mdx
Lots of Python packages make `replicate show` hard to use.
If there are interesting packages (tensorflow, torch, etc), show them. Otherwise, show at most 5. If `--all` is passed, show them all.
Looks a bit like this:
Any other ideas for "interesting" Python packages?
> Hide Python packages in show by default

- go/pkg/cli/common.go
- go/pkg/repository/repository.go
Initializing the S3/GCS library takes some time, so display a log
message immediately. This makes running all replicate commands feel
much snappier.
> Display "fetching" before initing repository

- python/keepsake/experiment.py
- python/tests/test_experiment.py
Rename the class `Experiment` methods `save` and `validate` to `_save` and `_validate` as pointed out in #64.
> Add underscore prefix to Experiment save and validate methods (#64)

- go/benchmark/list_test.go
- go/pkg/cli/daemon.go
- go/pkg/cli/root.go
- go/pkg/global/variables.go
- go/pkg/repository/s3.go
- go/pkg/repository/s3_test.go
Lets the user override the hardcoded s3 region (currently `us-east-1`).
> respect AWS_DEFAULT_REGION env var

- go/pkg/repository/repository.go
- go/pkg/repository/repository_test.go
- python/tests/test_experiment.py
> throw error if checkpointing missing file

- go/pkg/errors/errors.go
Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>
The `ConfigNotFound` error message had `"""` quotes at the end of URL which were redirecting to [https://keepsake.ai/docs/reference/python%22%22%22](https://keepsake.ai/docs/reference/python""") and this page is giving `404 Not Found`.
I am not sure if this is the expected behaviour 😅 
Python Version: 3.7 running on Jupyter Notebook
> Remove quotes from ConfigNotFound error message

- end-to-end-test/end_to_end_test/test_checkout.py
- go/pkg/cli/checkout.go
> fix checkout without experiment path
