python/replicate/repository/disk_repository.py
python/replicate/repository/gcs_repository.py
python/replicate/repository/s3_repository.py
python/tests/repository/test_disk_repository.py
python/tests/repository/test_gcs_repository.py
python/tests/repository/test_s3_repository.py

Signed-off-by: Andreas Jansson <andreas.s.t.jansson@gmail.com>

add python tests for tar get and put

---

python/replicate/constants.py
python/replicate/exceptions.py
python/replicate/validate.py

constants for documentation URLs in python

---

python/replicate/checkpoint.py
python/replicate/experiment.py
python/tests/factories.py
python/tests/test_checkpoint.py
web/pages/docs/reference/python.mdx

CheckpointList API with .metrics, .step, and .plot()

---

.github/workflows/ci.yaml

This is just a test of local branch to see if it runs external tests!

Use envvar in action to determine secrets

---

go/go.mod
go/pkg/repository/gcs.go

Add support for GOOGLE_APPLICATION_CREDENTIALS_JSON

---

python/replicate/config.py
python/replicate/experiment.py
python/tests/test_experiment.py
requirements-test.txt

Ran into this so fixed it.
Partial revert of ac6b78708964ce39f4e30e6eef3dbe5ed155a8c7
Fixes #319

Raise exceptions when creating experiment

---

CONTRIBUTING.md

Document project structure

---

CONTRIBUTING.md

Add "Where to start?" section to the contributing guide

---

.gitignore
go/pkg/config/load.go
go/pkg/config/load_test.go
go/pkg/global/variables.go
python/replicate/config.py
python/replicate/project.py
python/tests/test_config.py
python/tests/test_project.py

Support .yml extension for replicate.yaml #351

Support .yml extension for replicate.yaml 

---

go/Makefile

Signed-off-by: Ronit-j <pictronit007@gmail.com>

Add 'sudo' to resolve Linux-related permission error

---

python/replicate/experiment.py
web/pages/docs/guides/cloud-storage.mdx
web/styles/global.scss

Document how to store data in Colab notebooks

---

python/replicate/experiment.py
python/tests/test_experiment.py
web/pages/docs/reference/python.mdx

This is useful when you are doing analysis of an experiment that is running, and you want to get the latest data.

Add refresh() method to experiments

---

python/replicate/hash.py
python/tests/test_hash.py

fixes https://github.com/replicate/replicate/issues/417

include time in ID-generating hashing function

---

python/tests/repository/test_gcs_repository.py
python/tests/test_experiment.py

attempt to fix end-to-end tests that are flaky on CI

---

.github/workflows/ci.yaml
Makefile
end-to-end-test/end_to_end_test/test_checkout.py
end-to-end-test/end_to_end_test/test_delete.py
end-to-end-test/end_to_end_test/utils.py

This is bound to catch some edge cases.

Run CI on macOS

---

python/replicate/experiment.py
python/tests/test_experiment.py

Don't count checkpoints as best if their primary metric is NaN or None

---

go/pkg/cli/diff.go
go/pkg/cli/diff_test.go
go/pkg/cli/show_test.go
python/replicate/system.py

Added Python version to `diff` from #438 and changed to `sys.version_info`. 
Signed-off-by: kvthr <engg.ruthvik@gmail.com>

Add Python version to diff

---

go/pkg/shared/serve.go
python/replicate/daemon.py

... and a few related changes around quitting. Deets in commit messages.
[Details in this comment from #408.](https://github.com/replicate/replicate/pull/408#issuecomment-754850505)
Looks a bit like this:

Only display message on exit if work to be done

---

web/layouts/docs.js
web/pages/docs/guides/pytorch-lightning-integration.mdx

Link to PyTorch lightning docs

---

.github/workflows/ci.yaml
nodeps-test/Makefile
nodeps-test/test_nodeps.py
python/setup.py

This will fail until grpcio and google-common-protos are vendored.

test with no python dependencies installed

---

go/pkg/project/checkout.go

Fix inconsistent checkout message

---

go/pkg/files/files.go

Fixes https://github.com/replicate/replicate/issues/483

copy files without reading the whole thing into memory

---

go/pkg/cli/list.go
go/pkg/cli/list/list.go
go/pkg/param/filter.go
go/pkg/project/checkout.go
web/pages/docs/reference/cli.mdx

Filter name for creation time is called "started" instead of "created" #342

---

go/pkg/config/load.go

Fix grammar in error messages

---

python/setup.py
python/tests/test_pl_callback.py

Fix broken PyTorch Lightning test

---

python/keepsake/experiment.py
python/tests/test_plot.py
requirements-test.txt

Rebased version of #543
Closes #543
Closes #205

fixed overlapping plots issue

---

end-to-end-test/end_to_end_test/test_checkout.py
go/pkg/cli/checkout.go
go/pkg/cli/rm.go
go/pkg/console/global.go
go/pkg/console/interactive.go
python/tests/test_pl_callback.py

https://www.youtube.com/watch?v=Mme2Aya_6Bc

Fix checking out when user says no

---

.github/workflows/ci.yaml

Switch to new gcloud GitHub action

---

web/pages/docs/reference/python.mdx

Fixed markdown formatting to make the ref link work.
Signed-off-by: Sam Stevens <samuel.robert.stevens@gmail.com>

Fixed markdown format.
